# Generated by Django 6.0 on 2026-03-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('relationshipType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('referredType', models.CharField(blank=True, max_length=100, null=True)),
                ('href', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('relationshipType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('units', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('referredType', models.CharField(blank=True, max_length=100, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPlaceRefOrValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('referredType', models.CharField(blank=True, max_length=100, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSpecificationRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('referredType', models.CharField(blank=True, max_length=100, null=True)),
                ('href', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField(blank=True, null=True)),
                ('endDateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('value', models.JSONField(blank=True, null=True)),
                ('valueType', models.CharField(max_length=50)),
                ('relationships', models.ManyToManyField(blank=True, related_name='characteristics', to='resource_inventory_management.characteristicrelationship')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('isBundle', models.BooleanField(default=False)),
                ('isEnabled', models.BooleanField(default=True)),
                ('constraint', models.ManyToManyField(blank=True, related_name='features', to='resource_inventory_management.constraintref')),
                ('featureCharacteristic', models.ManyToManyField(related_name='features', to='resource_inventory_management.characteristic')),
                ('featureRelationship', models.ManyToManyField(blank=True, related_name='features', to='resource_inventory_management.featurerelationship')),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentRefOrValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('referredType', models.CharField(blank=True, max_length=100, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('attachmentType', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('mimeType', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='resource_inventory_management.quantity')),
                ('validFor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='resource_inventory_management.timeperiod')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRefOrValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmf_id', models.CharField(max_length=100)),
                ('referredType', models.CharField(blank=True, max_length=100, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('resourceVersion', models.CharField(blank=True, max_length=50, null=True)),
                ('startOperatingDate', models.DateTimeField(blank=True, null=True)),
                ('endOperatingDate', models.DateTimeField(blank=True, null=True)),
                ('activationFeature', models.ManyToManyField(blank=True, related_name='resources_activation', to='resource_inventory_management.feature')),
                ('attachment', models.ManyToManyField(blank=True, related_name='resources_attachment', to='resource_inventory_management.attachmentreforvalue')),
                ('note', models.ManyToManyField(blank=True, related_name='resources_note', to='resource_inventory_management.note')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resource_inventory_management.relatedplacereforvalue')),
                ('relatedParty', models.ManyToManyField(blank=True, related_name='resources', to='resource_inventory_management.relatedparty')),
                ('resourceCharacteristic', models.ManyToManyField(blank=True, related_name='resources_characteristic', to='resource_inventory_management.characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipType', models.CharField(max_length=100)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_relationships', to='resource_inventory_management.resourcereforvalue')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('href', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('resourceVersion', models.CharField(blank=True, max_length=50, null=True)),
                ('startOperatingDate', models.DateTimeField(blank=True, null=True)),
                ('endOperatingDate', models.DateTimeField(blank=True, null=True)),
                ('administrativeState', models.CharField(blank=True, default='unlocked', max_length=50)),
                ('operationalState', models.CharField(blank=True, default='enable', max_length=50)),
                ('resourceStatus', models.CharField(blank=True, default='available', max_length=50)),
                ('usageState', models.CharField(blank=True, default='idle', max_length=50)),
                ('activationFeature', models.ManyToManyField(blank=True, related_name='resources', to='resource_inventory_management.feature')),
                ('attachment', models.ManyToManyField(blank=True, related_name='resources_main', to='resource_inventory_management.attachmentreforvalue')),
                ('note', models.ManyToManyField(blank=True, related_name='resources_main', to='resource_inventory_management.note')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_main', to='resource_inventory_management.relatedplacereforvalue')),
                ('relatedParty', models.ManyToManyField(blank=True, related_name='resources_main', to='resource_inventory_management.relatedparty')),
                ('resourceCharacteristic', models.ManyToManyField(blank=True, related_name='resources_main', to='resource_inventory_management.characteristic')),
                ('resourceRelationship', models.ManyToManyField(blank=True, related_name='resources_main', to='resource_inventory_management.resourcerelationship')),
                ('resourceSpecification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_main', to='resource_inventory_management.resourcespecificationref')),
            ],
        ),
        migrations.AddField(
            model_name='featurerelationship',
            name='validFor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_relationships', to='resource_inventory_management.timeperiod'),
        ),
    ]
