# Generated by Django 6.0 on 2026-01-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vlan', models.PositiveIntegerField()),
                ('customer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=50)),
            ],
        ),
    ]
