# Generated by Django 6.0 on 2026-02-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='name',
            new_name='nameUpdateBy',
        ),
    ]
