# Generated by Django 6.0 on 2026-02-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag_set', '0003_tagrange_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan', models.PositiveIntegerField()),
                ('division', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('access_hs', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=200)),
                ('circ_no', models.CharField(max_length=200)),
                ('Service_id', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('vlan_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_set.tagrange')),
            ],
        ),
    ]
