# Generated by Django 6.0 on 2026-02-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='Service_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='access_hs',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='circ_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='customer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='division',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='service',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='speed',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='usage',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
