# Generated by Django 6.0 on 2026-04-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0005_historicaltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltag',
            name='access_hs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='access_hs',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
