# Generated by Django 5.2.15 on 2026-06-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0007_alter_historicaltag_id_alter_tag_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('configuration_type', models.CharField(max_length=100)),
                ('delivery_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='historicaltag',
            name='configuration_settings',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tag.configurationsettings'),
        ),
        migrations.AddField(
            model_name='tag',
            name='configuration_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='tag.configurationsettings'),
        ),
    ]
