# Generated by Django 6.0 on 2025-12-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vlan_start', models.PositiveIntegerField()),
                ('vlan_end', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_set.company')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_set.region')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan', models.PositiveIntegerField()),
                ('customer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('usage', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=50)),
                ('vlan_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_set.tagrange')),
            ],
        ),
    ]
