# Generated by Django 6.0 on 2025-12-30 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('data_center', '0001_initial'),
        ('tag_set', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagrange',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.RemoveField(
            model_name='tagrange',
            name='region',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='vlan_range',
        ),
        migrations.AddField(
            model_name='tagrange',
            name='datacenter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tag_ranges', to='data_center.datacenter'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
