# Generated by Django 6.0 on 2026-01-05 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_set', '0002_alter_tagrange_company_remove_tagrange_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagrange',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
