# Generated by Django 6.0 on 2026-02-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_set', '0003_tagrange_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='STag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tagrange',
            name='stags',
            field=models.ManyToManyField(blank=True, related_name='tag_ranges', to='tag_set.stag'),
        ),
    ]
