# Generated by Django 5.2.14 on 2026-05-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tag_set', '0008_alter_stag_id_alter_tagrange_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagrange',
            name='group',
        ),
        migrations.AddField(
            model_name='tagrange',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='tag_ranges', to='auth.group'),
        ),
    ]
