# Generated by Django 6.0 on 2026-02-25 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0002_alter_datacenter_region'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='datacenter',
            field=models.ForeignKey(
            "data_center.DataCenter",
            on_delete=models.PROTECT,
            null=True,
            blank=True,
        ),
        preserve_default=True,
       
        ),
    ]
