# Generated by Django 6.0 on 2026-02-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0002_alter_datacenter_region'),
        ('region', '0002_region_datacenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='data_center.datacenter'),
        ),
    ]
