# Generated by Django 6.0 on 2026-01-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_code_company_city_company_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_partner',
        ),
    ]
