# Generated by Django 6.0 on 2026-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companytype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
