# Generated by Django 5.2.14 on 2026-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_companytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enni',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
