# Generated by Django 6.0 on 2026-02-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='region',
            field=models.CharField(max_length=255),
        ),
    ]
