# Generated by Django 6.0 on 2026-03-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0003_alter_datacenter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
